# Production database configuration
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Connection pool settings
spring.datasource.hikari.pool-name=ProdHikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JWT secret for production
api.security.token.secret=${JWT_SECRET}