# Development database configuration
spring.datasource.url=jdbc:h2:mem:forumhub
spring.datasource.username=sa
spring.datasource.password=

# Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.connection.url=jdbc:h2:mem:forumhub;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.properties.hibernate.connection.username=sa
spring.jpa.properties.hibernate.connection.password=

# H2 Console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## Connection pool settings
spring.datasource.hikari.pool-name=DevHikariCP
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=10
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.connection-timeout=300000
#spring.datasource.hikari.validation-timeout=5000

# Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.activated=true

# JWT configuration for development
jwt.secret=SenhaParaAmbienteDeDesenvolvimento

# DevTools configuration
spring.devtools.add-properties=false
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
